name = "nekonymous"
main = "src/index.ts"
compatibility_date = "2024-08-19"

workers_dev = true

kv_namespaces = [
  { binding = "NekonymousKV", id = "4bc98daad8eb4902b912227707f98f2b" },
]

[placement]
mode = "smart"

[vars]


# [durable_objects]
# bindings = [{ name = "INBOX_DO", class_name = "InboxDurableObject" }]

# [[migrations]]
# tag = "v1"                           # Increment this tag each time you make changes to Durable Objects
# new_classes = ["InboxDurableObject"]

[durable_objects]
bindings = [{ name = "CHAT_STATE", class_name = "ChatState" }]

[[migrations]]
tag = "v1"
new_classes = ["ChatState"]

[[d1_databases]]
binding = "DB"
database_name = "bdb"
database_id = "5fcbd2ea-f3a7-4e91-aa21-6a4c884b1732"
